name: "IdiotPluginPack1"
main: dev.longshotdev.idiot.teamPlugin.IdiotTeamPlugin
version: 1.0
api-version: 1.13
commands:
   aa:
      description: Your description
      usage: /aa
   createteams:
      description: create team
      permission: ipp.admin
      usage: /createteams {id} {name}
   getteams:
      description: get teams
      usage: /getteams
   tinfo:
      description: get info on teams
      usage: /tinfo fuckyou
   addplayertoteam:
      description: add player to which team
      permission: ipp.admin
      usage: /addplayertoteam {Player} {teamid}
   tpa:
      description: Send a teleport request to a player on the server.
      aliases: [tpr, tprequest]
      permission: ipp.tpa
      permission-message: You do not have permission to use this command!
   tpaccept:
      description: Accept a teleport request.
      aliases: accept
      permission: ipp.tpaccept
      permission-message: You do not have permission to use this command!
   tpdeny:
      description: Deny a teleport request.
      aliases: deny
      permission: ipp.tpdeny
      permission-message: You do not have permission to use this command!

      
permissions:
  ipp.tpa:
    description: Allows you to use the /tpa command.
    default: true
  ipp.tpaccept:
    description: Allows you to use the /tpaccept command.
    default: true
  ipp.tpdeny:
    description: Allows you to use the /tpdeny command.
    default: true
  ipp.admin:
     description: be admin
     default: true
    
depend: [ProtocolLib]